"""Training pipeline for Hearts ML models.

This is a fixed pipeline that students do not modify. It reads game
data generated by the data generator, converts it to feature vectors
using a FeatureExtractor, and trains a RandomForestClassifier.

Students are encouraged to read this file to understand what's
happening, but their task is feature engineering in features.py —
not modifying this pipeline.
"""

from __future__ import annotations

import json
import os
import pickle
import sys
import warnings
from pathlib import Path
from typing import Callable, Optional

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


def _safe_n_jobs() -> int:
    """Choose n_jobs to avoid memory pressure from parallel RF workers.

    Each worker gets a copy of the training data. With large datasets
    on machines with limited RAM, n_jobs=-1 (all cores) can cause
    swapping and catastrophic slowdowns. This caps parallelism so that
    estimated memory stays under ~60% of system RAM.
    """
    try:
        # Each worker needs roughly: n_samples * n_features * 8 bytes
        # We don't know the dataset size here, so use a conservative
        # heuristic: cap at 4 jobs, or fewer on low-memory machines.
        n_cpus = os.cpu_count() or 1
        # Try to read available memory (works on macOS and Linux)
        try:
            import resource
            # On macOS, sysctl is more reliable
            mem_bytes = os.sysconf("SC_PAGE_SIZE") * os.sysconf(
                "SC_PHYS_PAGES"
            )
        except (ValueError, OSError, AttributeError):
            mem_bytes = 16 * 1024**3  # assume 16 GB

        mem_gb = mem_bytes / (1024**3)
        # Allow ~1 GB per worker as a rough budget
        max_by_mem = max(1, int(mem_gb // 4))
        return min(n_cpus, max_by_mem, 4)
    except Exception:
        return 2

from hearts.data.schema import deserialize_player_view
from hearts.ml.features import FeatureExtractor


def load_data(data_dir: str | Path) -> list[dict]:
    """Read play_decisions.jsonl and return a list of records.

    Each record is a dict with all fields from the JSONL file,
    including the serialized PlayerView, the card played, and
    outcome annotations.
    """
    path = Path(data_dir) / "play_decisions.jsonl"
    records = []
    with open(path) as f:
        for line in f:
            records.append(json.loads(line))
    return records


def build_dataset(
    records: list[dict],
    extractor: FeatureExtractor,
    progress: Optional[Callable[[int, int], None]] = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Convert raw records into feature matrix X and label vector y.

    For each record, reconstructs the PlayerView from the serialized
    JSON, calls the extractor to produce a feature vector, and uses
    the card_played field as the label.

    Args:
        records: list of dicts from load_data()
        extractor: the feature extractor to apply
        progress: optional callback(current, total) for progress

    Returns:
        X: array of shape (n_samples, n_features)
        y: array of shape (n_samples,) with card indices (0-51)
    """
    total = len(records)
    if total == 0:
        return np.array([]), np.array([])

    # Check if the extractor supports a fast path that skips
    # deserialization (works directly on the raw dict with int indices).
    fast = extractor.extract_from_record(records[0])
    use_fast = fast is not None

    if use_fast:
        n_features = len(fast)
        X = np.empty((total, n_features), dtype=np.float32)
        y = np.empty(total, dtype=np.int32)
        X[0] = fast
        y[0] = records[0]["card_played"]

        for i in range(1, total):
            X[i] = extractor.extract_from_record(records[i])
            y[i] = records[i]["card_played"]
            if progress is not None and (
                (i + 1) % 5000 == 0 or i + 1 == total
            ):
                progress(i + 1, total)
    else:
        # Standard path: deserialize each record to PlayerView first.
        first_view = deserialize_player_view(records[0])
        first_features = extractor.extract(first_view)
        n_features = len(first_features)

        X = np.empty((total, n_features), dtype=np.float32)
        y = np.empty(total, dtype=np.int32)
        X[0] = first_features
        y[0] = records[0]["card_played"]

        for i in range(1, total):
            view = deserialize_player_view(records[i])
            X[i] = extractor.extract(view)
            y[i] = records[i]["card_played"]
            if progress is not None and (
                (i + 1) % 5000 == 0 or i + 1 == total
            ):
                progress(i + 1, total)

    return X, y


def train_model(
    X: np.ndarray,
    y: np.ndarray,
    feature_names: list[str],
    seed: Optional[int] = None,
) -> tuple[RandomForestClassifier, dict]:
    """Train a RandomForestClassifier on the dataset.

    Uses an 80/20 train/test split. The model is fixed — no
    hyperparameter tuning, no model selection.

    Args:
        X: feature matrix (n_samples, n_features)
        y: label vector (n_samples,)
        feature_names: names for each feature dimension
        seed: random seed for reproducibility

    Returns:
        Tuple of (trained model, metrics dict). The metrics dict
        contains train_accuracy, test_accuracy, and
        feature_importances (sorted by importance descending).
    """
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=seed
    )

    n_jobs = _safe_n_jobs()
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=15,
        min_samples_leaf=20,
        random_state=seed,
        n_jobs=n_jobs,
    )
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore",
            message="`sklearn.utils.parallel.delayed`",
            category=UserWarning,
        )
        model.fit(X_train, y_train)

    train_accuracy = model.score(X_train, y_train)
    test_accuracy = model.score(X_test, y_test)

    importances = model.feature_importances_
    feature_importances = sorted(
        zip(feature_names, importances),
        key=lambda x: x[1],
        reverse=True,
    )

    return model, {
        "train_accuracy": train_accuracy,
        "test_accuracy": test_accuracy,
        "feature_importances": feature_importances,
        "n_train": len(X_train),
        "n_test": len(X_test),
        "n_features": X.shape[1],
        "n_jobs": n_jobs,
    }


def save_model(
    model: RandomForestClassifier,
    extractor_class_name: str,
    metrics: dict,
    path: str | Path,
) -> None:
    """Save the trained model, extractor class name, and metrics.

    The extractor class name is saved so that evaluation can
    reconstruct the correct extractor when loading the model.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump(
            {
                "model": model,
                "extractor_class_name": extractor_class_name,
                "metrics": metrics,
            },
            f,
        )


def load_model(
    path: str | Path,
) -> tuple[RandomForestClassifier, str, dict]:
    """Load a saved model, extractor class name, and metrics.

    Returns:
        Tuple of (model, extractor_class_name, metrics).
    """
    with open(path, "rb") as f:
        data = pickle.load(f)
    return data["model"], data["extractor_class_name"], data["metrics"]
